### PR TITLE
Fix for Bug : null geometry for correct node geometries

### LINKED ISSUE #13: Bug in Geom Update Script
With @omranlm  's test ,Currently somehow our script is replacing null with already existing correct node geometries , Need to fix it

### PR DESCRIPTION
**Pull request by kshitijrajsharma**
- Resolve #13 
- Calculates way feature geometry with new construct geometry function
Can be tested with following sample query for one month  : 

- Sample Command to run script : 

  `python geom_update.py -start '2020-01-01' -end '2020-12-30'`
```
select
	*,
	case
        when (
            oeh.type = 'node' 
            and (oeh.geom = ST_MakePoint(oeh.lat, oeh.lon) or oeh.geom is null)
        ) then ST_MakePoint(oeh.lon, oeh.lat)
        when oeh.type = 'way'  then public.construct_geometry(
            oeh.id,
            oeh.version,
            oeh."timestamp",
            oeh.nds,
            oeh.changeset      
        )
        else oeh.geom
	end geom2
from
	osm_element_history as oeh
where
	oeh.action != 'delete'
	and oeh.type != 'relation'
	and oeh."timestamp" >= '2020-02-09 19:54:13'
	and oeh."timestamp" < '2020-03-09 19:54:13'
```

### CODE REVIEW

**Review by omranlm — CHANGES_REQUESTED** [review]
As discussed, Let's have the frequency and start and end date as parameters for the script so we can focus on specific time period to update the geom.
the "else" part is amazing to avoid writing null 
And for the "way" feature, lets always update it as we have a new version of construct_geometry function with this signature 
`public.construct_geometry(row_id int8, ver int8,way_date "timestamp",_nds int8[],p_changeset int8)`

**Comment by itskshitiz321** [comment]
Added start and end as parameter , monthly as default frequency . I haven't added frequency as parameter for now as monthly seems fine ! We can always change since it is just a parameter to the function *Restricted to Enum Values for now *

**Comment by itskshitiz321** [comment]
Script now runs backward . Frequency added as argument  
Sample script command will be : 
`python geom_update.py -start '2020-12-30' -end '2020-01-01' -f 'm'`

**Review by omranlm — APPROVED** [review]
looks great 
The arguments and scanning backwords looks fine as well

**Pull request merged**
